DROP DATABASE IF EXISTS soccer;

CREATE DATABASE soccer;

\c soccer

CREATE TABLE teams
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE players
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  team_id INTEGER REFERENCES teams ON DELETE SET NULL
);

CREATE TABLE referees
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE season
(
  id SERIAL PRIMARY KEY,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL
);

CREATE TABLE games
(
  id SERIAL PRIMARY KEY,
  team1_id INTEGER REFERENCES teams ON DELETE NO ACTION,
  team2_id INTEGER REFERENCES teams ON DELETE NO ACTION,
  date TEXT,
  season_id INTEGER REFERENCES season ON DELETE CASCADE,
  winner_id INTEGER REFERENCES teams ON DELETE NO ACTION
);

CREATE TABLE referees_games
(
  id SERIAL PRIMARY KEY,
  ref_id INTEGER REFERENCES referees ON DELETE NO ACTION,
  game_id INTEGER REFERENCES games ON DELETE CASCADE
);

CREATE TABLE goals
(
  id SERIAL PRIMARY KEY,
  player_id INTEGER REFERENCES players ON DELETE CASCADE,
  game_id INTEGER REFERENCES games ON DELETE CASCADE
);